//created on: Aug 5, 2021
package model

//list any import classes here.

import model.*;

//declare any global variables here




rule "Next Step"
    when
        $f : FacilityAgent( demo_step != 0 )
        $m : ManagerAgent()
        $e : EligibilityAgent()
        $p : ProviderAgent()
        $s : ServiceAgent()
        $l : LevelOfCareAgent()
        $n : MedNecAgent()
    then
        $m.nextStep();
        $e.nextStep();
        $p.nextStep();
        $s.nextStep();
        $l.nextStep();
        $n.nextStep();
end

rule "Reset" salience 1
    when
        $f : FacilityAgent( demo_step == 0 )
        $m : ManagerAgent()
        $e : EligibilityAgent()
        $p : ProviderAgent()
        $s : ServiceAgent()
        $l : LevelOfCareAgent()
        $n : MedNecAgent()
    then
    	System.out.println("RESET");
    	$f.setDemo_step(0);
        $m.setDemo_step(0);
        $e.setDemo_step(0);
        $p.setDemo_step(0);
        $s.setDemo_step(0);
        $l.setDemo_step(0);
        $n.setDemo_step(0);
end

/*rule "Facility"
	when
		FacilityAgent()
	then
		System.out.println("Facility ONLINE");
end

rule "Manager"
	when
		ManagerAgent()
	then
		System.out.println("Manager ONLINE");
end

rule "Elig"
	when
		EligibilityAgent()
	then
		System.out.println("Eligibility ONLINE");
end

rule "Provider"
	when
		ProviderAgent()
	then
		System.out.println("Provider ONLINE");
end

rule "Service"
	when
		ServiceAgent()
	then
		System.out.println("Service ONLINE");
end

rule "LevelOfCare"
	when
		LevelOfCareAgent()
	then
		System.out.println("LevelOfCare ONLINE");
end

rule "MedNec"
	when
		MedNecAgent()
	then
		System.out.println("MedNec ONLINE");
end*/
