//created on: Jul 16, 2021
package model

//list any import classes here.

import model.ProviderAgent 
import jade.core.AID;
import jade.lang.acl.ACLMessage;

//declare any global variables here




rule "Confirm manager Message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), ConversationId.equals("first-info") )
		$m : ProviderAgent( aidNameOnly.equals($r) )
	then
		System.out.println("Rule - Info Message recieved from "+$send+" sent to "+$r);
		//Approval
		ACLMessage prov = new ACLMessage(ACLMessage.AGREE);
		prov.addReceiver($m.getManager());
		prov.setContent("looks good");
		prov.setConversationId("provider-approval");
		$m.send(prov);
		retract($a);		
end
