//created on: Jul 16, 2021
package model

//list any import classes here.
import model.EligibilityAgent;
import data.MedicalInfo;
import data.Patient;

import jade.lang.acl.ACLMessage;
import jade.core.AID;

//declare any global variables here





rule "Initial message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), $c : content, ConversationId.equals("initial-info") )
		$e : EligibilityAgent( name.equals(((AID)$r).getName()) )
	then
		$e.parseForm($c);
		retract($a);		
end

rule "Missing name"
	when
		$p : Patient( firstName.equals("") || lastName.equals("") )
	then
		System.out.println("Missing name");
end

rule "Check name"
	when 
		$p : Patient( $f : firstName, $l : lastName )
		$i : MedicalInfo( $m : medication, $d : diagnosis )
	then
		System.out.println("Patient: " + $l + ", " +$f);
end

rule "Check treatment"
	when 
		$i : MedicalInfo( $m : medication, $d : diagnosis )
	then
		System.out.println("Treatment: " + $m + " for " +$d);
end