//created on: Jul 16, 2021
package model

//list any import classes here.
import model.EligibilityAgent;
import jade.lang.acl.ACLMessage;
import jade.core.AID;

//declare any global variables here




rule "Your First Rule"

    when
        EligibilityAgent()
    then
        System.out.println("Eligibility Agent exists");
end

rule "Initial message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), $c : content, ConversationId.equals("initial-info") )
		$e : EligibilityAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Eligibility got the message");
		$e.parseForm($c);
		retract($a);		
end