//created on: Jul 16, 2021
package model
 
//list any import classes here.

import model.MedNecAgent
import jade.core.AID
import jade.lang.acl.ACLMessage

//declare any global variables here




rule "Mednec Message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), ConversationId.equals("first-info") )
		$m : MedNecAgent( aidNameOnly.equals($r) )
	then
		System.out.println("Rule - Info Message recieved from "+$send+" sent to "+$r);
		//Approval
		ACLMessage med = new ACLMessage(ACLMessage.AGREE);
		med.addReceiver($m.getLevelofcare());
		med.setContent("all good");
		med.setConversationId("med-decision");
		$m.send(med);
		retract($a);		
end
