//created on: Jul 16, 2021
package model

//list any import classes here.
import model.ManagerAgent;
import jade.lang.acl.ACLMessage;
import jade.core.AID;

//declare any global variables here




rule "Your First Rule"

    when
        ManagerAgent()
    then
        System.out.println("Manager Agent exists");
end

rule "PA Form"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("facility-pa-request"), $send.equals("Facility") )
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got PA Request from " + $send);
		$m.breakdownForm($c);
		retract($a);		
end
