//created on: Jul 16, 2021
package model
import model.ManagerAgent 
//list any import classes here.



//declare any global variables here




rule "Your First Rule"

    when
        ManagerAgent()
    then
        System.out.println("Manager Agent exists");
end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
