//created on: Jul 16, 2021
package model

//list any import classes here.
import model.ManagerAgent;
import jade.lang.acl.ACLMessage;
import jade.core.AID;

//declare any global variables here





rule "PA Form"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("facility-pa-request") )
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got PA Request from " + $send);
		$m.breakdownForm($c);
		retract($a);		
end

rule "Eligibility Approval"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("eligibility-approval"))
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got approval from the eligibility agent!");
		retract($a);		
end

rule "Eligibility Denial"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("eligibility-denial"))
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got denial from the eligibility agent...");
		retract($a);		
end

rule "Provider Approval"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("provider-approval"))
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got approval from the provider agent!");
		retract($a);		
end

rule "Provider Denial"
	when
		$a : ACLMessage( $send : sender.localName, $r : AllReceiver.next(), $c : content, ConversationId.equals("provider-denial"))
		$m : ManagerAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Manager got denial from the provider agent...");
		
		retract($a);		
end

