//created on: Jul 16, 2021
package model

//list any import classes here.
import model.ServiceAgent;
import data.MedicalInfo;
import data.Patient;
import jade.lang.acl.ACLMessage;
import jade.core.AID;

//declare any global variables here




rule "Your First Rule"

    when
        ServiceAgent()
    then
        System.out.println("Service Agent exists");
end

rule "Initial message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), $c : content, ConversationId.equals("initial-info") )
		$s : ServiceAgent( name.equals(((AID)$r).getName()) )
	then
		System.out.println("Service got the message");
		$s.parseForm($c);
		retract($a);		
end

rule "Send cpt and icd codes"
	when
		$m : MedicalInfo( !cptCode.equals(""), !icd10Codes.equals(""), $c : cptCode, $i : icd10Codes )
		$p : Patient ( hospitalized != null, $h : hospitalized )
		$s : ServiceAgent( )
	then
		//System.out.println("Success both cpt and icd");
		$s.quickMessage($s.getLevelofcare(), $s, $c + "-" + $i + "-" + String.valueOf($h), "med-codes");
		$s.quickMessage($s.getMednec(), $s, $c + "-" + $i, "med-codes");
end

rule "Missing cpt and icd codes"
	when
		$m : MedicalInfo( cptCode.equals("") || icd10Codes.equals("") )
		$s : ServiceAgent( )
	then
		System.out.println("Missing cpt/icd");
		$s.missingInfo("cpt_code,icd_10");
end
		
		
		
		