//created on: Jul 16, 2021
package model

//list any import classes here.

import model.ServiceAgent 
import jade.core.AID
import jade.lang.acl.ACLMessage

//declare any global variables here




rule "Manager Message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), ConversationId.equals("first-info") )
		$m : ServiceAgent( aidNameOnly.equals($r) )
	then
		System.out.println("Rule - Info Message recieved from "+$send+" sent to "+$r);
		//Approval
		ACLMessage serv = new ACLMessage(ACLMessage.INFORM);
		serv.addReceiver($m.getLevelofcare());
		serv.setContent("here's some info");
		serv.setConversationId("first-info");
		$m.send(serv);
		retract($a);		
end

rule "Levelofcare Message"
	when
		$a : ACLMessage( $send : sender.name, $r : AllReceiver.next(), ConversationId.equals("care-decision") )
		$m : ServiceAgent( aidNameOnly.equals($r) )
	then
		System.out.println("Rule - Info Message recieved from "+$send+" sent to "+$r);
		//Approval
		ACLMessage serv = new ACLMessage(ACLMessage.AGREE);
		serv.addReceiver($m.getManager());
		serv.setContent("all good");
		serv.setConversationId("service-approval");
		$m.send(serv);
		retract($a);		
end
